### ISSUE TITLE
Relay Just stopped issuing commands

### ISSUE THREAD

**Issue by ryancasler** [greghesp/assistant-relay#28]
Has something changed with the assistant SDK?  Because commands that worked an hour ago are no longer working and the console shows that the commands are being issued correctly by assistant relay.  What's the deal?

**Comment by josharmour** [comment]
Same here, just stopped working for me.

Got this in the console when I tried to run it:


pi@raspberrypi:~/assistant-relay-master/assistant-relay $ npm run start

> assistant-relay@1.0.1 start /home/pi/assistant-relay-master/assistant-relay
> node index.js

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/home/pi/assistant-relay-master/assistant-relay/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pi/assistant-relay-master/assistant-relay/index.js:151:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! assistant-relay@1.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the assistant-relay@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-05-15T04_51_46_377Z-debug.log
pi@raspberrypi:~/assistant-relay-master/assistant-relay $

**Comment by josharmour** [comment]
`pi@raspberrypi:~/assistant-relay-master/assistant-relay $ cat /home/pi/.npm/_logs/2018-05-15T04_51_46_377Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle assistant-relay@1.0.1~prestart: assistant-relay@1.0.1
6 info lifecycle assistant-relay@1.0.1~start: assistant-relay@1.0.1
7 verbose lifecycle assistant-relay@1.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle assistant-relay@1.0.1~start: PATH: /opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/assistant-relay-master/assistant-relay/node_modules/.bin:/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle assistant-relay@1.0.1~start: CWD: /home/pi/assistant-relay-master/assistant-relay
10 silly lifecycle assistant-relay@1.0.1~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle assistant-relay@1.0.1~start: Returned: code: 1  signal: null
12 info lifecycle assistant-relay@1.0.1~start: Failed to exec start script
13 verbose stack Error: assistant-relay@1.0.1 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid assistant-relay@1.0.1
15 verbose cwd /home/pi/assistant-relay-master/assistant-relay
16 verbose Linux 4.9.35-v7+
17 verbose argv "/opt/nodejs/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v9.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error assistant-relay@1.0.1 start: `node index.js`
22 error Exit status 1
23 error Failed at the assistant-relay@1.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
pi@raspberrypi:~/assistant-relay-master/assistant-relay $
`

**Comment by josharmour** [comment]
This fixed it for me: 

 Update available 5.6.0 → 6.0.1    │
   │     Run npm i -g npm to update

**Comment by josharmour** [comment]
Here is the output of running node index.js

`root@raspberrypi:/home/pi/assistant-relay-master/assistant-relay# node index.js
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/home/pi/assistant-relay-master/assistant-relay/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/pi/assistant-relay-master/assistant-relay/index.js:151:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
`

**Comment by ryancasler** [comment]
That is not the problem.  That is because you already have one instance of assistant relay running also.  Stop your auto-started method and then look at the log.   Or then start manually.  No errors are being posted.

**Comment by josharmour** [comment]
So I tried to stop it following these instructions: https://stackoverflow.com/questions/9898372/how-to-fix-error-listen-eaddrinuse-while-using-nodejs

You are right, after stopping it looks like it starts but I hear no broadcast.

pi@raspberrypi:~/assistant-relay-master/assistant-relay $ killall -9 node
node: no process found
pi@raspberrypi:~/assistant-relay-master/assistant-relay $ node index.js         Firing up the Web Server for communication on address 192.168.86.248:3000
Assistant Relay is now setup and running for josh
Received command broadcast Assistant Relay is now setup and running for josh
No user specified, using josh

**Comment by ryancasler** [comment]
Yup, that's the problem.

**Comment by incrediblemolk** [comment]
Same issue here, been working fine for months until sometime yesterday or today.  Now no broadcast commands are spoken by the Google Home.

**Comment by ryancasler** [comment]
Yeah, I've tried everything I can think of.  Updating node, that didn't work.  updating raspbian, that didn't work.  Something had to change on the google side of things.

**Comment by josharmour** [comment]
Yeah, I bet its the way that assistant relay and Google interact.

**Comment by DanDon** [comment]
Same problem here ... seems as though Google have updated something as the Node.js console is spitting out all the right stuff but no broadcast to the Google homes :(

**Comment by AnuragJindal** [comment]
i am seeing the same issue. The relay shows response on the terminal but no announcement from google home.

**Comment by chriswalker01** [comment]
Same, same. Has anyone found a fix or any clues?

**Comment by ryancasler** [comment]
Nope.

**Comment by DanDon** [comment]
I have raised this issue as a ticket with Google as it does not work even on Google Assistant on phones. The response is "Something went wrong". 
The TTS broadcast feature has broken Google end and they tested themselves while I was talking to them and confirmed the issue.
They are looking into resolving it.

**Comment by ryancasler** [comment]
Thank you!

**Comment by josharmour** [comment]
Interesting my Google home is able to broadcast at home..  I'm able to make
a broadcast on my Google homes for my phone at home as well..

**Comment by DanDon** [comment]
@josharmour Yes but only by voice. If you type the broadcast message into assistant it will not work.

**Comment by josharmour** [comment]
Ahh..  We use broadcast all the time in my house "kid's its time for
dinner", "honey bring me my coffee please", "good morning".. All of it
works from everywhere for me except from this assistant relay node server
for me.  :(

I do see that 3 days ago the GRPC node package and the assistant node
package were updated, I bet that it's not a total Google outage, and more
likely that clients that use those packages need to update to the new
version.

https://www.npmjs.com/package/google-assistant-node

https://www.npmjs.com/package/grpc

**Comment by ryancasler** [comment]
That is not correct.  If you go into the Assistant app on your phone and activate the keyboard so that you can type in commands and you type "broadcast wakeup" it will not work.

**Comment by josharmour** [comment]
Looks like they changed the name of the package as well from
google-assistant to google-assistant-node.  I'm uninstalling the old
version and installing the new module.

**Comment by josharmour** [comment]
You can talk about typing in commands into the assistant app all you want
but it doesn't change what node modules have been updated at the exact time
that this node project went down :)  Also, note these instructions from the
author:

https://community.smartthings.com/t/release-google-assistant-relay-google-home-audio-notifications/114674/826

He seems to think its the package as well.

**Comment by ryancasler** [comment]
If the assistant isn't taking text commands then it won't take text commands from anywhere.  So, update whatever packages you want, you will never get it to work.

**Comment by josharmour** [comment]
Ahh, got your logic.  Ok, my understanding was that the voice commands that
are given to the voice server are passed along to the assistant as text the
same way.  Also, I was under the impression that this project use the node
js endpoint which is not the same endpoint that the google assistant app on
android uses.

Apologies.

**Comment by ryancasler** [comment]
No, if you look at the code that he uses...theres a like at the end of the readme...it's the embedded Assistant SDK.  Basically, he is mimicing another GH device on the network to issue the commands.  That's how he's able to "trick" it.

**Comment by josharmour** [comment]
Yep, just looking at that repo right now :)

https://github.com/endoplasmic/google-assistant

I can maybe ping some of my co-workers about it.

**Comment by josharmour** [comment]
I suppose it may make more sense to just integrate directly into the node
module for google-assistant as long as it support broadcasts.

**Comment by ryancasler** [comment]
okay....#1 do you know how to program in node?  cause i sure as hell don't.  and #2, do you even know what you're talking about?  LMAO

**Comment by josharmour** [comment]
haha, I think we are in a similar boat, except I may have co-workers that
can help since I've been at Google for 11 years.

Looks like the author of that project just gave Greg the right answer..

"oh @greghesp <https://github.com/greghesp>, they actually added support
for sending text queries now. Just add textQuery to the conversation object
and you'll be good to go.

You can also check out the console-input example."

https://github.com/endoplasmic/google-assistant/issues/52#issuecomment-390372604

**Comment by greghesp** [comment]
Looks like a simple fix. I'll push an update when I'm home

**Comment by josharmour** [comment]
@greghesp I think this is the line that needs updated?  https://github.com/greghesp/assistant-relay/blob/master/devicetypes/greghesp/assistant-relay.src/assistant-relay.groovy#L55

**Comment by ryancasler** [comment]
From @endoplasmic 

> The broadcast functionality has changed since now it actually streams your voice to all the google homes in your home, before you could send text using the assistant's voice.
> 
> It also looks like you can't broadcast from the SDK, so maybe they will re-add that back in

**Comment by josharmour** [comment]
Yeah,

I've poked around a little bit to see if folks can clue me in..

**Comment by ryancasler** [comment]
Did you even read what he wrote?!?  LMAO.  You keep poking dude.  Eventually you're realize the futility.

**Comment by josharmour** [comment]
I did read what he wrote, and I'm trying to help.  What I mean by poking is
pinging the product team.  It may be futile, or maybe they'll respond.
Just like you opened a bug with Google, I'm trying another method to get
some help.

Note, this update brings up that the broadcast function is gone from grpc
*service* but its still available using the native library.
https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/188
points to https://developers.google.com/assistant/sdk/overview#features

You can see what platforms support broadcasts.

Is it possible that we can get assistant-relay to not rely on grpc service
and maybe move to a native library implementation?

**Comment by josharmour** [comment]
Well I poked around some, and it is being fixed.  I'll let you know when I can share more.

**Comment by DanDon** [comment]
@josharmour Not sure what has been fixed? It is still the same?

**Comment by greghesp** [comment]
It's not been fixed, it's going to be fixed. Knowing Google though, we might be waiting a while..

**Comment by josharmour** [comment]
I'm tracking it, I'll let you know when I know an ETA and can share it.

**Comment by josharmour** [comment]
Ok, I think it should be working now.  Let me know @greghesp

**Comment by chriswalker01** [comment]
Broadcasts by typing in the Google Assistant app are working again for me but not via the Assistant Relay. Is it the same for everyone else?

**Comment by jymbob** [comment]
@chriswalker01 yep, same here, UK. [Google Activity log](https://myactivity.google.com/myactivity) records a response to a broadcast request from Google Assistant SDK as: "Sorry, it looks like I can't broadcast at the moment.
You might want to try again later."

**Comment by greghesp** [comment]
Yep same here.

Looks like its not fixed on Google's side @josharmour.  They still need to fix it for the SDK

**Comment by chathurangawijetunge** [comment]
Any luck....? When will relay will be up and running as usual...?

**Comment by greghesp** [comment]
Literally commented 3 hours before you asked saying its waiting for Google.

Can I suggest people upvote this question to make it more visible:
https://stackoverflow.com/questions/50428892/google-assistant-sdk-c-broadcast-command

**Comment by chathurangawijetunge** [comment]
Hi guy's until google fix this issue use https://github.com/noelportugal/google-home-notifier

It also works.

**Comment by greghesp** [comment]
@josharmour 
Seems another thing is broken via text:
https://github.com/greghesp/assistant-relay/issues/30#issuecomment-391652206

**Comment by mhofman** [comment]
@chathurangawijetunge sorry but that just uses the cast function of Google Home devices. It is not the same as broadcast a message, which does not interrupt music already playing.

**Comment by mhofman** [comment]
According to [Google Assistant SDK overview](https://developers.google.com/assistant/sdk/overview), the gRPC service does not support broadcast messages. It is not clear however if it means just playback of broadcast message, or also initialization of broadcasts. Would be good to get a clarification from Google, and if the latter, get it fixed.

**Comment by ryancasler** [comment]
Yes, no fix as of yet.  Still broken on the within the Google Assistant SDK.

**Comment by josharmour** [comment]
Hey guys.  Apologies I can't give more info other than the team is aware of
these threads and discussing.  I'll share more when I can.

**Comment by jpoeppelman1** [comment]
Has this node module been updated to use the python library?  When will this be resolved?  Thanks.

**Comment by greghesp** [comment]
No.  There is a thread where the issue is being discussed
https://github.com/endoplasmic/google-assistant/issues/52

**Comment by greghesp** [comment]
Issue has been fixed by Google. Assistant relay is back up and running

**Comment by esalomo** [comment]
Hi,
Did something change last night in the API? 
Starting this morning All my automated broadcast messages announcements starting with "Message from xxxxx : "Actual specific text message" while before that it was simply announcing the specific text message only - I did not change anything anywhere - not in the node.js server or WebCore.... 
Any insight will be helpful as it sounds annoying as it is now.

**Comment by greghesp** [comment]
Nothing to do with me. I assume Google have done something their end as you'll soon be able to reply to broadcasts I believe

**Comment by esalomo** [comment]
Thanks Greg, so it means that we now stuck with the specific username at the beginning of all the text broadcast messages which are going through the relay?
I tested the announcement feature via the std. google home interface (voice commanding the device t "broadcast a message" and in this scenario, there is no username in the announcement at the beginning of the broadcast so why it is different via the relay?

**Comment by greghesp** [comment]
If you do a voice command, it broadcasts your voice so I guess people should know what you sound like.  If you send a text broadcast via assistant, it says "Broadcast from" before TTS'ing the message :(

**Comment by esalomo** [comment]
ok, it means we need to get used to this annoying new thing :(
I assume that cast-web-api will have the same issue....

**Comment by jymbob** [comment]
Cast web uses a different protocol so will probably be unaffected. Unlike
broadcasting, your current activity won't resume after something else is
cast

**Comment by esalomo** [comment]
Ok got it thanks!

Thanks,
Eran S.

________________________________
